"""Add new columns to videos table

Revision ID: bea06c1778e9
Revises: 
Create Date: 2025-10-28 11:18:45.163152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea06c1778e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('rating', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('duration', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('backdrop_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'backdrop_url')
    op.drop_column('videos', 'duration')
    op.drop_column('videos', 'rating')
    op.drop_column('videos', 'year')
    # ### end Alembic commands ###
